### ISSUE TITLE
bad-cb-no-2nd-out

### ISSUE THREAD

**Issue by peysab** [freecashorg/freecash#10]
When trying to submit a block getting the following error: bad-cb-no-2nd-out

Any ideas?

**Comment by freecashorg** [comment]
fch has at least 2 coinbase vout, and 'i=1' is fixed as the 'FCH governing funding' 
see   https://github.com/freecashorg/freecash/wiki/Freecash区块结构-及-挖矿协议改进

**Comment by freecashorg** [comment]
'bad-cb-no-2nd-out' means the size of coinbase vout was less then 2
