### ISSUE TITLE
mining pool software

### ISSUE THREAD

**Issue by BobZombiE69** [freecashorg/freecash#11]
Where can i find the software to run on the pool , so miners can mine FCH ?

I tried CK software
https://bitbucket.org/ckolivas/ckpool

, it works fine with BCH, but it's not compatible with FCH.

**Comment by akshaynexus** [comment]
My fork of miningcore has most of the changes needed,but is missing proper coinbasedevreward payment ,ive opened a pr to add the necessary info miningcore needs to get the decoded payee and hence have a open source mining pool for FCH.

**Comment by caisirius** [comment]
please check : https://freecash.vip/index.aspx?lang=en
