### ISSUE TITLE
mined block coin-base 25 FCH reward still immature_balance after 3000 confirmations !

### ISSUE THREAD

**Issue by BobZombiE69** [freecashorg/freecash#13]
Can some one please help me, 
I'm mining FCH , i found lots of blocks , just in 1 wallet i mined 7 blocks.
**The blocks submitted and confirmed, but it's still showing as immature_balance in my wallet.**
here is the block explorer link to my wallet, you can see all blocks are confirmed:
[https://freecash.info/address?address=FF4dCu4CUGberkmu8RdH7GYJiFrZhtuWwU](url)

Here is my FCH version:

```freecash-cli -datadir=/opt/newcoin/ -getinfo
{
  "version": 1000400,
  "protocolversion": 70015,
  "walletversion": 190700,
  "balance": 0.00000000,
  "blocks": 157879,
```

and here are one of the mined blocks, which the reward is still immature !!!
you can see it has : **"confirmations": 2939** and **"category": "immature",**
```{
    "account": "bobi",
    "address": "FF4dCu4CUGberkmu8RdH7GYJiFrZhtuWwU",
    "category": "immature",
    "amount": 25.00000000,
    "label": "bobi",
    "vout": 0,
    "confirmations": 2939,
    "generated": true,
    "blockhash": "00000000000000006747470c8fe9cf0d3928d1b2de0084198a3f68a4893a7a08",
    "blockindex": 0,
    "blocktime": 1587137855,
    "txid": "146b502174284e05a0a32c0c3b3ceade7d44385df0223a13d029ea20302ce319",
    "walletconflicts": [
    ],
    "time": 1587137855,
    "timereceived": 1587137880
  }
```

and here is my wallet info: **"immature_balance": 175.00000000,**
```freecash-cli -datadir=/opt/newcoin/ getwalletinfo
{
  "walletname": "",
  "walletversion": 190700,
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 175.00000000,
  "txcount": 7,
```

**Comment by dimazzzv** [comment]
I have the same Issue
"walletname": "",
  "walletversion": 190700,
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 75.00000000,
  "txcount": 3,
  "keypoololdest": 1587431782,
--------------------------
i use that instruction for my NOMP
 https://bbs.cash/topic/13/%E6%90%AD%E5%BB%BAnomp-fch%E7%A7%81%E6%B1%A0%E5%9B%BE%E6%96%87%E6%95%99%E7%A8%8B-%E9%87%8D%E8%A6%81%E6%9B%B4%E6%96%B0-%E8%B6%85%E9%B8%A1%E8%AF%A6%E7%BB%86-%E6%9C%89%E5%8A%A8%E6%89%8B%E8%83%BD%E5%8A%9B%E7%9A%84%E6%9D%A5/2
--------------------------
and all blocks are in immature status
  here is decoded block:
{
  "txid": "0f196ebf3971fbc6ddd31132ac15a150fdd999e3fbec04d9fbce5895cc0eb3cc",
  "hash": "0f196ebf3971fbc6ddd31132ac15a150fdd999e3fbec04d9fbce5895cc0eb3cc",
  "version": 1,
  "size": 180,
  "locktime": 0,
  "vin": [
    {
      "coinbase": "03227a0204f899a05e0827ffffe5c4b4010008646d7a76706f6f6c",
      "sequence": 0
    }
  ],
  "vout": [
    {
      "value": 23.75000000,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 0d00dae91ac52b87cfcee41b83c9a0225fce45a5 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a9140d00dae91ac52b87cfcee41b83c9a0225fce45a588ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "F71sGi8PSzeMq9sb4jJn4B1sckdY6XvDMr"
        ]
      }
    },
    {
      "value": 25.00000000,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 f1704a9663c1e530f82ca1bc7ff52f0f65abc1ca OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a914f1704a9663c1e530f82ca1bc7ff52f0f65abc1ca88ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "FTqiqAyXHnK7uDTXzMap3acvqADK4ZGzts"
        ]
      }
    },
    {
      "value": 1.25000000,
      "n": 2,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 73b1dbd04cb58e9553c2489c125ab98bf694f318 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a91473b1dbd04cb58e9553c2489c125ab98bf694f31888ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "FGNrEhQ4PCqMv4NGsP7F5T6R24PSpNjcsG"
        ]
      }
    }
  ]
}
https://freecash.info/address?address=F71sGi8PSzeMq9sb4jJn4B1sckdY6XvDMr
what i do wrong?

**Comment by BobZombiE69** [comment]
WTF ! 
it seems that FCH needs 10 days !!! to mature 
so after 10 days you can spend it

who will mine a currency and sell after 10 days ! what if the price goes down in 10 day !

**Comment by dimazzzv** [comment]
> it seems that FCH needs 10 days !!! to mature
> so after 10 days you can spend it

where you find this information?

**Comment by caisirius** [comment]
Yes,  FCH coinbase needs 10 days to mature.

**Comment by caisirius** [comment]
mining reward needs 10 days to mature. This is rule of fch
